server:
  port: 8080
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
    lazy-initialization: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# JWT配置
jwt:
  secret: your_jwt_secret_key_here
  expiration: 86400000  # 24小时

# 第三方API配置
api:
  xunfei:
    app_id: your_xunfei_app_id
    api_key: your_xunfei_api_key
  amap:
    key: your_amap_api_key
  llm:
    api_key: your_llm_api_key